version: '3.3'
services:
  customers:
    container_name: 'users'
    image: 'lab/users:1.0.0'
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://172.18.0.2:5432/lab
      - QUARKUS_DATASOURCE_USERNAME=dev
      - QUARKUS_DATASOURCE_PASSWORD=secret123.
      - TZ=America/Santiago
    ports:
      - '8000:8000'
    restart: unless-stopped